### ISSUE TITLE
Doesn't work in YAML

### ISSUE THREAD

**Issue by Suor** [colinta/SublimeChangeQuotes#13]
```python
Traceback (most recent call last):
  File "change_quotes in /home/suor/.config/sublime-text-3/Installed Packages/ChangeQuotes.sublime-package", line 48, in run
  File "change_quotes in /home/suor/.config/sublime-text-3/Installed Packages/ChangeQuotes.sublime-package", line 106, in run_each
KeyError: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "change_quotes in /home/suor/.config/sublime-text-3/Installed Packages/ChangeQuotes.sublime-package", line 50, in run
AttributeError: 'KeyError' object has no attribute 'message'
```

Also error handling fails as you can see.

**Comment by colinta** [comment]
Please provide more details:  What steps you took, what did you expect and what *actually* happened, what does your YAML look like, are you using ST2 or ST3, etc.  I use this plugin a ton, I've never seen these errors.
